// ===== CASH COUNTER =====
function calcCash() {
  let total = 0;
  [2000,500,200,100,50,20,10,5,2,1].forEach(n => {
    const qty = +document.getElementById(`note-${n}`).value || 0;
    const amt = qty * n;
    document.getElementById(`res-${n}`).innerText = `₹${amt}`;
    total += amt;
  });
  document.getElementById("grandTotal").innerText = total.toLocaleString("en-IN");
}

function resetCash() {
  [2000,500,200,100,50,20,10,5,2,1].forEach(n => {
    document.getElementById(`note-${n}`).value = "";
    document.getElementById(`res-${n}`).innerText = "₹0";
  });
  document.getElementById("grandTotal").innerText = "0";
  showNotify("info","Counter Cleared");
}

async function handlePrint() {
  const total = document.getElementById("grandTotal").innerText;
  if (!total || total === "0") return showNotify("error","Amount cannot be 0!");
  let rows = "";
  [2000,500,200,100,50,20,10,5,2,1].forEach(n => {
    const qty = document.getElementById(`note-${n}`).value || 0;
    if (qty > 0) rows += `<tr><td>₹${n}</td><td>${qty}</td><td>₹${qty*n}</td></tr>`;
  });
  const win = window.open("","_blank");
  win.document.write(`<html><body style="font-family:Arial;padding:20px"><h2>SwiftTool Pro - Cash Receipt</h2><hr><table border="1" cellpadding="8" style="width:100%;border-collapse:collapse"><tr><th>Note</th><th>Count</th><th>Total</th></tr>${rows}<tr><td colspan="2"><b>Grand Total</b></td><td><b>₹${total}</b></td></tr></table><br><p>Generated by SwiftTool Pro</p></body></html>`);
  win.document.close(); win.print();
}

// ===== QR CODE =====
function generateQR() {
  const text = document.getElementById("qrText").value.trim();
  if (!text) return showNotify("error","Please enter text or URL!");
  const url = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(text)}`;
  document.getElementById("qrResult").innerHTML = `<img src="${url}" class="img-fluid rounded shadow" style="max-width:200px"><br><a href="${url}" download="qrcode.png" class="btn btn-sm btn-outline-dark mt-3"><i class="fas fa-download me-1"></i>Download QR</a>`;
  showNotify("success","QR Code Ready!");
}

function resetQR() {
  document.getElementById("qrText").value = "";
  document.getElementById("qrResult").innerHTML = "";
}

// ===== AGE CALCULATOR =====
function calculateAge() {
  const dob = new Date(document.getElementById("dob").value);
  const target = new Date(document.getElementById("todayDate").value);
  if (!document.getElementById("dob").value) return showNotify("error","Select Date of Birth!");
  if (dob > target) return showNotify("error","DOB cannot be in the future!");

  let y = target.getFullYear() - dob.getFullYear();
  let m = target.getMonth() - dob.getMonth();
  let d = target.getDate() - dob.getDate();
  if (d < 0) { m--; d += new Date(target.getFullYear(), target.getMonth(), 0).getDate(); }
  if (m < 0) { y--; m += 12; }

  document.getElementById("ageResult").classList.remove("d-none");
  document.getElementById("mainAge").innerText = `${y} Years`;
  document.getElementById("extraAge").innerText = `${m} Months, ${d} Days`;
  const diff = Math.abs(target - dob);
  document.getElementById("totalMonths").innerText = (y*12+m).toLocaleString();
  document.getElementById("totalWeeks").innerText = Math.floor(diff/(1000*60*60*24*7)).toLocaleString();
  document.getElementById("totalDays").innerText = Math.floor(diff/(1000*60*60*24)).toLocaleString();
  showNotify("success","Age Calculated!");
}

// ===== MISC HELPERS =====
function updateQDisplay(v) { document.getElementById("qValue").innerText = Math.round(v*100)+"%"; }
function previewImage() {
  const f = document.getElementById("compressInput").files[0];
  if (!f) return;
  const r = new FileReader();
  r.onload = e => { document.getElementById("previewArea").innerHTML = `<img src="${e.target.result}" class="img-fluid rounded" style="max-height:120px"><p class="small text-muted mt-1">${(f.size/1024).toFixed(1)} KB</p>`; };
  r.readAsDataURL(f);
}
function resetPDFTool() { document.getElementById("imageInput").value = ""; showNotify("info","Cleared"); }
function resetCompressor() {
  document.getElementById("compressInput").value = "";
  document.getElementById("qualityRange").value = 0.7;
  document.getElementById("qValue").innerText = "70%";
  document.getElementById("previewArea").innerHTML = "Preview";
  showNotify("info","Cleared");
}
function resetPdfToImg() {
  document.getElementById("pdfInput").value = "";
  document.getElementById("pdfPreview").innerHTML = "";
  document.getElementById("downloadAllBtn").classList.add("d-none");
  showNotify("info","Cleared");
}
function resetResizer() {
  const i = document.getElementById("resizeInput"); if(i) i.value = "";
  const p = document.getElementById("resPreview"); if(p) p.innerHTML = "";
  document.getElementById("targetSize").value = "50";
  showNotify("info","Cleared");
}
function resetTool(name, btn) { openTool(name); }
function previewResize() {
  const f = document.getElementById("resizeInput").files[0];
  if (!f) return;
  const r = new FileReader();
  r.onload = e => {
    document.getElementById("resPreview").innerHTML = `<img src="${e.target.result}" class="img-fluid rounded shadow-sm" style="max-height:150px"><p class="small text-muted mt-1">${(f.size/1024).toFixed(1)} KB</p>`;
  };
  r.readAsDataURL(f);
}

// ===== WORD COUNTER =====
function updateWordCount() {
  const text = document.getElementById("wcText").value;
  const words = text.trim() ? text.trim().split(/\s+/).length : 0;
  const chars = text.length;
  const sentences = text.split(/[.!?]+/).filter(s => s.trim()).length;
  const readTime = Math.ceil(words / 200);
  document.getElementById("wcWords").innerText = words.toLocaleString();
  document.getElementById("wcChars").innerText = chars.toLocaleString();
  document.getElementById("wcSentences").innerText = sentences.toLocaleString();
  document.getElementById("wcReadTime").innerText = readTime || 0;
}

// ===== PASSWORD GENERATOR =====
function generatePassword() {
  const len = +document.getElementById("pwdLen").value;
  const upper = document.getElementById("pwdUpper").checked;
  const lower = document.getElementById("pwdLower").checked;
  const num = document.getElementById("pwdNum").checked;
  const sym = document.getElementById("pwdSym").checked;
  if (!upper && !lower && !num && !sym) return showNotify("error","Select at least one character type!");
  let chars = "";
  if (upper) chars += "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  if (lower) chars += "abcdefghijklmnopqrstuvwxyz";
  if (num) chars += "0123456789";
  if (sym) chars += "!@#$%^&*()_+-=[]{}|;:,.<>?";
  let pwd = "";
  for (let i = 0; i < len; i++) pwd += chars[Math.floor(Math.random() * chars.length)];
  document.getElementById("pwdOutput").value = pwd;
  // Strength
  const strength = [upper,lower,num,sym].filter(Boolean).length;
  const pct = [0,25,50,75,100][strength];
  const colors = ["","#dc3545","#fd7e14","#ffc107","#198754"];
  const labels = ["","Weak","Fair","Good","Strong"];
  const bar = document.getElementById("pwdStrBar");
  bar.style.width = pct+"%"; bar.style.background = colors[strength];
  document.getElementById("pwdStrLabel").innerText = labels[strength];
  document.getElementById("pwdStrLabel").style.color = colors[strength];
  document.getElementById("pwdStrength").classList.remove("d-none");
}

function copyPassword() {
  const v = document.getElementById("pwdOutput").value;
  if (!v) return showNotify("error","Generate a password first!");
  navigator.clipboard.writeText(v).then(() => showNotify("success","Password Copied!"));
}

// ===== BASE64 =====
function doBase64(mode) {
  const input = document.getElementById("b64Input").value.trim();
  if (!input) return showNotify("error","Enter some text first!");
  let result = "";
  try {
    result = mode === "encode" ? btoa(unescape(encodeURIComponent(input))) : decodeURIComponent(escape(atob(input)));
  } catch(e) { return showNotify("error","Invalid Base64 input for decoding!"); }
  document.getElementById("b64Output").value = result;
  document.getElementById("b64Result").classList.remove("d-none");
  showNotify("success", mode === "encode" ? "Encoded!" : "Decoded!");
}

// ===== UNIT CONVERTER =====
const UC_UNITS = {
  length: { m:1, km:0.001, cm:100, mm:1000, inch:39.3701, ft:3.28084, yard:1.09361, mile:0.000621371 },
  weight: { kg:1, g:1000, mg:1e6, lb:2.20462, oz:35.274, ton:0.001 },
  temperature: { celsius:1, fahrenheit:1, kelvin:1 },
  area: { sqm:1, sqkm:1e-6, sqft:10.7639, sqyard:1.19599, acre:0.000247105, hectare:0.0001 },
  speed: { mps:1, kph:3.6, mph:2.23694, knot:1.94384 }
};

function updateUnitOptions() {
  const cat = document.getElementById("ucCategory").value;
  const units = Object.keys(UC_UNITS[cat]);
  const labels = { m:"Meter",km:"Kilometer",cm:"Centimeter",mm:"Millimeter",inch:"Inch",ft:"Foot",yard:"Yard",mile:"Mile",kg:"Kilogram",g:"Gram",mg:"Milligram",lb:"Pound",oz:"Ounce",ton:"Ton",celsius:"Celsius (°C)",fahrenheit:"Fahrenheit (°F)",kelvin:"Kelvin (K)",sqm:"Sq. Meter",sqkm:"Sq. Kilometer",sqft:"Sq. Foot",sqyard:"Sq. Yard",acre:"Acre",hectare:"Hectare",mps:"m/s",kph:"km/h",mph:"mph",knot:"Knot" };
  const opts = units.map(u => `<option value="${u}">${labels[u]||u}</option>`).join("");
  document.getElementById("ucFrom").innerHTML = opts;
  document.getElementById("ucTo").innerHTML = opts;
  document.getElementById("ucTo").value = units[1] || units[0];
  document.getElementById("ucResult").value = "";
}

function convertUnit() {
  const cat = document.getElementById("ucCategory").value;
  const from = document.getElementById("ucFrom").value;
  const to = document.getElementById("ucTo").value;
  const val = parseFloat(document.getElementById("ucValue").value);
  if (isNaN(val)) { document.getElementById("ucResult").value = ""; return; }
  let result;
  if (cat === "temperature") {
    let celsius;
    if (from === "celsius") celsius = val;
    else if (from === "fahrenheit") celsius = (val-32)*5/9;
    else celsius = val - 273.15;
    if (to === "celsius") result = celsius;
    else if (to === "fahrenheit") result = celsius*9/5+32;
    else result = celsius + 273.15;
  } else {
    const base = val / UC_UNITS[cat][from];
    result = base * UC_UNITS[cat][to];
  }
  document.getElementById("ucResult").value = parseFloat(result.toFixed(6));
}

// ===== LOREM IPSUM =====
const LOREM_WORDS = "lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat non proident sunt in culpa qui officia deserunt mollit anim id est laborum".split(" ");

function generateLorem() {
  const type = document.getElementById("loremType").value;
  const count = Math.min(+document.getElementById("loremCount").value || 3, 50);
  let output = "";
  const rw = (n) => Array.from({length:n}, () => LOREM_WORDS[Math.floor(Math.random()*LOREM_WORDS.length)]).join(" ");
  const rs = () => { const s = rw(Math.floor(Math.random()*12)+6); return s.charAt(0).toUpperCase()+s.slice(1)+"."; };
  const rp = () => Array.from({length:Math.floor(Math.random()*4)+4}, rs).join(" ");
  if (type === "words") output = rw(count);
  else if (type === "sentences") output = Array.from({length:count}, rs).join(" ");
  else output = Array.from({length:count}, rp).join("\n\n");
  document.getElementById("loremOutput").value = output;
  document.getElementById("loremResult").classList.remove("d-none");
  showNotify("success","Text Generated!");
}

// ===== SHOW EXTRA PAGES =====
function showExtra(page) {
  const titles = { about:"About Us", privacy:"Privacy Policy", terms:"Terms of Service", contact:"Contact Us" };
  document.title = (titles[page]||page) + " | SwiftTool Pro";
  history.pushState({page}, "", `#${page}`);

  ["toolsGrid","activeTool","heroSection","statsSection","seoContent"].forEach(id => {
    const el = document.getElementById(id);
    if (el) el.classList.add("d-none");
  });

  const extraScreens = document.getElementById("extraScreens");
  const content = document.getElementById("extraContent");
  if (!extraScreens || !content) return;
  extraScreens.classList.remove("d-none");
  extraScreens.removeAttribute("style");
  window.scrollTo({top:0,behavior:"smooth"});

  const pages = {
    about: `<h2 class="fw-bold text-primary mb-3 border-bottom pb-2">About SwiftTool Pro</h2>
      <p class="lead text-muted">SwiftTool Pro is a free, browser-based digital toolkit built for students, professionals, and everyday users across India.</p>
      <h5 class="fw-bold mt-4">Our Story</h5>
      <p>SwiftTool Pro was created with one simple goal — to give every Indian internet user access to powerful digital tools without paying a rupee, without creating an account, and without worrying about their private files being uploaded to unknown servers.</p>
      <p>Whether you're a student preparing for SSC or UPSC exams who needs to resize a photo to exactly 20KB, a small business owner who needs to calculate GST quickly, or a developer who needs a Base64 encoder — SwiftTool Pro has you covered.</p>
      <h5 class="fw-bold mt-4">What Makes Us Different</h5>
      <p>Unlike most online tools that upload your files to their servers, <strong>SwiftTool Pro processes everything locally in your browser</strong>. Your PDFs, images, and documents never leave your device. This means complete privacy, faster processing, and zero risk of data leaks.</p>
      <div class="row g-3 mt-2">
        <div class="col-md-6"><div class="feature-card"><div class="feature-icon" style="background:#ede9fe"><i class="fas fa-shield-halved text-primary"></i></div><h6 class="fw-bold">Privacy First</h6><p class="small text-muted mb-0">100% client-side processing. Your files never leave your browser.</p></div></div>
        <div class="col-md-6"><div class="feature-card"><div class="feature-icon" style="background:#dcfce7"><i class="fas fa-bolt text-success"></i></div><h6 class="fw-bold">23+ Free Tools</h6><p class="small text-muted mb-0">PDF, Image, Finance, and Utility tools — all completely free.</p></div></div>
        <div class="col-md-6"><div class="feature-card"><div class="feature-icon" style="background:#fef3c7"><i class="fas fa-graduation-cap text-warning"></i></div><h6 class="fw-bold">Built for India</h6><p class="small text-muted mb-0">Specialized tools for SSC, UPSC, IBPS, Railway exam portals.</p></div></div>
        <div class="col-md-6"><div class="feature-card"><div class="feature-icon" style="background:#fce7f3"><i class="fas fa-mobile-alt text-danger"></i></div><h6 class="fw-bold">Works Everywhere</h6><p class="small text-muted mb-0">Mobile, tablet, desktop — any modern browser on any device.</p></div></div>
      </div>
      <h5 class="fw-bold mt-4">Our Tools</h5>
      <p>SwiftTool Pro currently offers 23+ free tools across four categories:</p>
      <ul>
        <li><strong>Image Tools:</strong> Exam Photo Resizer (20KB/50KB), Image Compressor, Images to PDF, Image to Text (OCR)</li>
        <li><strong>PDF Tools:</strong> Merge PDF, Split PDF, PDF to Image, Remove PDF Pages</li>
        <li><strong>Finance Tools:</strong> EMI Calculator, GST Calculator, Cash Counter</li>
        <li><strong>Utility Tools:</strong> QR Code Generator, Age Calculator, Word Counter, Password Generator, Unit Converter, Percentage Calculator, Text Case Converter, Stopwatch & Timer, Base64 Encoder/Decoder, Lorem Ipsum Generator, AI Voice Reader</li>
      </ul>
      <p class="mt-3 text-muted small">SwiftTool Pro is maintained independently and supported by advertising revenue through Google AdSense. This allows us to keep all tools free for everyone.</p>`,

    privacy: `<h2 class="fw-bold mb-3 border-bottom pb-2">Privacy Policy</h2>
      <p class="small text-muted">Last Updated: March 2026</p>
      <p>SwiftTool Pro ("we", "our", or "us") is committed to protecting your privacy. This policy explains how we handle information when you use our website at <strong>swifttoolpro.com</strong>.</p>

      <h5 class="fw-bold mt-4 text-primary">1. No File Storage — Zero Server Uploads</h5>
      <p>SwiftTool Pro uses 100% client-side processing. When you use any of our tools (PDF converter, image resizer, OCR, etc.), your files are processed entirely within your browser's memory. <strong>No file is ever uploaded to our servers.</strong> When you close the tab, all data is cleared automatically.</p>

      <h5 class="fw-bold mt-4 text-primary">2. Google AdSense (Advertising)</h5>
      <p>We use <strong>Google AdSense</strong> to display advertisements on our website. Google AdSense uses cookies and web beacons to serve ads based on your prior visits to our website and other websites on the internet. Google's use of advertising cookies enables it and its partners to serve ads based on your visit to our site and/or other sites on the Internet.</p>
      <p>You may opt out of personalized advertising by visiting <a href="https://www.google.com/settings/ads" target="_blank" rel="noopener">Google Ads Settings</a>. You can also opt out of a third-party vendor's use of cookies for personalized advertising by visiting <a href="https://www.aboutads.info" target="_blank" rel="noopener">www.aboutads.info</a>.</p>

      <h5 class="fw-bold mt-4 text-primary">3. Google Analytics</h5>
      <p>We use <strong>Google Analytics</strong> to understand how visitors use our website. Google Analytics collects information such as how often users visit the site, what pages they visit, and what other sites they used prior to coming to our site. We use this information to improve our website. Google Analytics collects only the IP address assigned to you on the date you visit this site, not your name or other identifying information.</p>

      <h5 class="fw-bold mt-4 text-primary">4. Cookies</h5>
      <p>Our website uses cookies for the following purposes:</p>
      <ul>
        <li><strong>Analytics cookies</strong> — Google Analytics uses cookies to track usage patterns</li>
        <li><strong>Advertising cookies</strong> — Google AdSense uses cookies to show relevant ads</li>
        <li><strong>Functional cookies</strong> — We store your recently used tools in localStorage for convenience</li>
      </ul>
      <p>You can control cookies through your browser settings. Disabling cookies may affect some functionality.</p>

      <h5 class="fw-bold mt-4 text-primary">5. Third-Party Services</h5>
      <p>Our tools use the following third-party JavaScript libraries that run entirely in your browser: PDF.js, PDF-lib, Tesseract.js, Mammoth.js, JSZip. None of these libraries transmit your data to external servers.</p>

      <h5 class="fw-bold mt-4 text-primary">6. Children's Privacy</h5>
      <p>SwiftTool Pro does not knowingly collect any personal information from children under 13 years of age.</p>

      <h5 class="fw-bold mt-4 text-primary">7. Changes to This Policy</h5>
      <p>We may update this Privacy Policy from time to time. Changes will be posted on this page with an updated date.</p>

      <h5 class="fw-bold mt-4 text-primary">8. Contact Us</h5>
      <p>If you have questions about this Privacy Policy, please use our <a href="javascript:void(0)" onclick="showExtra('contact')">Contact Us</a> form.</p>`,

    terms: `<h2 class="fw-bold mb-3 border-bottom pb-2">Terms of Service</h2>
      <p class="small text-muted">Last Updated: March 2026</p>
      <p>Please read these Terms of Service carefully before using SwiftTool Pro at <strong>swifttoolpro.com</strong>.</p>

      <h5 class="fw-bold mt-4 text-primary">1. Acceptance of Terms</h5>
      <p>By accessing or using SwiftTool Pro, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our website.</p>

      <h5 class="fw-bold mt-4 text-primary">2. Description of Service</h5>
      <p>SwiftTool Pro provides free, browser-based digital utility tools including PDF tools, image tools, finance calculators, and utility tools. All tools are provided free of charge and process data locally in your browser.</p>

      <h5 class="fw-bold mt-4 text-primary">3. Acceptable Use</h5>
      <p>You agree to use SwiftTool Pro only for lawful purposes. You must not use our tools to:</p>
      <ul>
        <li>Process, distribute, or store illegal content</li>
        <li>Infringe on any copyright, trademark, or intellectual property rights</li>
        <li>Attempt to reverse engineer, hack, or disrupt our website</li>
        <li>Use automated scripts or bots to access our tools</li>
      </ul>

      <h5 class="fw-bold mt-4 text-primary">4. Intellectual Property</h5>
      <p>The SwiftTool Pro name, logo, design, and original content are owned by SwiftTool Pro. Third-party libraries used (PDF.js, Tesseract.js, etc.) are subject to their respective open-source licenses.</p>

      <h5 class="fw-bold mt-4 text-primary">5. Disclaimer of Warranties</h5>
      <p>SwiftTool Pro is provided "as is" without any warranties of any kind. We do not guarantee that our tools will produce results accepted by third-party portals (such as government exam websites). Always verify output before submission.</p>

      <h5 class="fw-bold mt-4 text-primary">6. Limitation of Liability</h5>
      <p>SwiftTool Pro shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of our tools or inability to use our tools.</p>

      <h5 class="fw-bold mt-4 text-primary">7. Advertising</h5>
      <p>SwiftTool Pro displays advertisements through Google AdSense to support the free service. By using our website, you consent to the display of these advertisements.</p>

      <h5 class="fw-bold mt-4 text-primary">8. Changes to Terms</h5>
      <p>We reserve the right to modify these terms at any time. Continued use of the website after changes constitutes acceptance of the new terms.</p>

      <h5 class="fw-bold mt-4 text-primary">9. Contact</h5>
      <p>For questions about these terms, please use our <a href="javascript:void(0)" onclick="showExtra('contact')">Contact Us</a> form.</p>`,

    contact: `<h2 class="fw-bold text-primary mb-3 border-bottom pb-2">Contact Us</h2>
      <div class="row g-4">
        <div class="col-md-5">
          <div class="feature-card h-100">
            <div class="d-flex mb-3"><div class="feature-icon me-3" style="background:#ede9fe"><i class="fas fa-headset text-primary"></i></div><div><h6 class="fw-bold mb-0">Support</h6><p class="small text-muted mb-0">Use the form to reach us. We respond within 24–48 hours.</p></div></div>
            <div class="d-flex mb-3"><div class="feature-icon me-3" style="background:#dcfce7"><i class="fas fa-clock text-success"></i></div><div><h6 class="fw-bold mb-0">Response Time</h6><p class="small text-muted mb-0">Within 24-48 hours</p></div></div>
            <div class="d-flex"><div class="feature-icon me-3" style="background:#fef3c7"><i class="fas fa-map-marker-alt text-warning"></i></div><div><h6 class="fw-bold mb-0">Location</h6><p class="small text-muted mb-0">India</p></div></div>
          </div>
        </div>
        <div class="col-md-7">
          <form id="contact-form" action="https://formspree.io/f/xbdayrne" method="POST" class="bg-white p-4 rounded-4 shadow-sm border">
            <div class="row g-3">
              <div class="col-md-6"><label class="form-label fw-bold small">Name</label><input type="text" name="name" class="form-control" placeholder="Your Name" required></div>
              <div class="col-md-6"><label class="form-label fw-bold small">Email</label><input type="email" name="email" class="form-control" placeholder="your@email.com" required></div>
              <div class="col-12"><label class="form-label fw-bold small">Message</label><textarea name="message" class="form-control" rows="4" placeholder="How can we help?" required></textarea></div>
              <div class="col-12"><button type="submit" id="form-submit" class="btn btn-primary w-100 fw-bold py-3">Send Message <i class="fas fa-paper-plane ms-2"></i></button></div>
            </div>
          </form>
        </div>
      </div>`
  };

  content.innerHTML = `<div class="animate__animated animate__fadeIn text-start">${pages[page]||"<p>Page not found.</p>"}</div>`;
  if (page === "contact") {
    const form = document.getElementById("contact-form");
    if (form) form.onsubmit = async e => {
      e.preventDefault();
      const btn = document.getElementById("form-submit");
      btn.disabled = true; btn.innerHTML = '<span class="spinner-border spinner-border-sm me-2"></span>Sending...';
      try {
        const res = await fetch(form.action, {method:"POST",body:new FormData(form),headers:{"Accept":"application/json"}});
        if (res.ok) { showNotify("success","Message sent!"); form.reset(); }
        else showNotify("error","Something went wrong.");
      } catch { showNotify("error","Connection error."); }
      btn.disabled = false; btn.innerHTML = 'Send Message <i class="fas fa-paper-plane ms-2"></i>';
    };
  }
}

window.onpopstate = () => { if (!location.hash && location.pathname === "/") goToDashboard(); };

// ===== EMI CALCULATOR =====
function calcEMI() {
  const P = parseFloat(document.getElementById("emiAmount").value);
  const annualRate = parseFloat(document.getElementById("emiRate").value);
  const n = parseInt(document.getElementById("emiTenure").value);
  const res = document.getElementById("emiResult");
  if (!P || !annualRate || !n || P <= 0 || annualRate <= 0 || n <= 0) { res.classList.add("d-none"); return; }

  const r = annualRate / 12 / 100;
  const emi = P * r * Math.pow(1+r, n) / (Math.pow(1+r, n) - 1);
  const total = emi * n;
  const interest = total - P;

  const fmt = v => "₹" + Math.round(v).toLocaleString("en-IN");
  document.getElementById("emiMonthly").textContent = fmt(emi);
  document.getElementById("emiTotalAmt").textContent = fmt(total);
  document.getElementById("emiInterest").textContent = fmt(interest);

  const pPct = Math.round((P / total) * 100);
  const iPct = 100 - pPct;
  document.getElementById("emiProgressBar").style.width = pPct + "%";
  document.getElementById("emiInterestBar").style.width = iPct + "%";
  document.getElementById("emiPrincipalBar").textContent = `Principal ${pPct}% | Interest ${iPct}%`;

  // Amortization table
  let balance = P, rows = "";
  for (let i = 1; i <= n; i++) {
    const intPart = balance * r;
    const prinPart = emi - intPart;
    balance -= prinPart;
    rows += `<tr><td>${i}</td><td>${fmt(emi)}</td><td>${fmt(prinPart)}</td><td>${fmt(intPart)}</td><td>${fmt(Math.max(0,balance))}</td></tr>`;
  }
  document.getElementById("emiTableBody").innerHTML = rows;
  res.classList.remove("d-none");
}

function resetEMI() {
  ["emiAmount","emiRate","emiTenure"].forEach(id => document.getElementById(id).value = "");
  document.getElementById("emiResult").classList.add("d-none");
}

// ===== IMAGE TO TEXT (OCR) =====
function runOCR(file) {
  if (!file) return;
  const reader = new FileReader();
  reader.onload = function(e) {
    const img = document.getElementById("ocrPreviewImg");
    img.src = e.target.result;
    document.getElementById("ocrPreviewBox").classList.remove("d-none");
    document.getElementById("ocrProgress").classList.remove("d-none");
    document.getElementById("ocrResultBox").classList.add("d-none");

    Tesseract.recognize(e.target.result, "eng", {
      logger: m => {
        if (m.status === "recognizing text") {
          const pct = Math.round(m.progress * 100);
          document.getElementById("ocrBar").style.width = pct + "%";
          document.getElementById("ocrPct").textContent = pct + "%";
        }
      }
    }).then(({ data: { text } }) => {
      document.getElementById("ocrProgress").classList.add("d-none");
      document.getElementById("ocrOutput").value = text.trim() || "(No text detected)";
      document.getElementById("ocrResultBox").classList.remove("d-none");
      showNotify("success", "Text extracted!");
    }).catch(() => {
      document.getElementById("ocrProgress").classList.add("d-none");
      showNotify("error", "OCR failed. Try a clearer image.");
    });
  };
  reader.readAsDataURL(file);
}

function resetOCR() {
  document.getElementById("ocrInput").value = "";
  document.getElementById("ocrPreviewBox").classList.add("d-none");
  document.getElementById("ocrProgress").classList.add("d-none");
  document.getElementById("ocrResultBox").classList.add("d-none");
  document.getElementById("ocrOutput").value = "";
}

function downloadOCRText() {
  const text = document.getElementById("ocrOutput").value;
  if (!text) return showNotify("error", "No text to download!");
  const blob = new Blob([text], { type: "text/plain" });
  const a = document.createElement("a"); a.href = URL.createObjectURL(blob);
  a.download = "extracted_text.txt"; a.click();
}

// ===== PERCENTAGE CALCULATOR =====
function calcPct1() {
  const x = parseFloat(document.getElementById("pct1X").value);
  const y = parseFloat(document.getElementById("pct1Y").value);
  document.getElementById("pct1Res").textContent = (!isNaN(x) && !isNaN(y)) ? ((x/100)*y).toFixed(2) : "—";
}
function calcPct2() {
  const from = parseFloat(document.getElementById("pct2From").value);
  const to   = parseFloat(document.getElementById("pct2To").value);
  if (!isNaN(from) && !isNaN(to) && from !== 0) {
    const diff = ((to - from) / Math.abs(from)) * 100;
    const el = document.getElementById("pct2Res");
    el.textContent = (diff >= 0 ? "▲ +" : "▼ ") + diff.toFixed(2) + "%";
    el.style.color = diff >= 0 ? "#16a34a" : "#dc2626";
  } else { document.getElementById("pct2Res").textContent = "—"; }
}
function calcPct3() {
  const m = parseFloat(document.getElementById("pctMarks").value);
  const t = parseFloat(document.getElementById("pctTotal").value);
  document.getElementById("pct3Res").textContent = (!isNaN(m) && !isNaN(t) && t > 0) ? ((m/t)*100).toFixed(2) + "%" : "—";
}
function calcPct4() {
  const p = parseFloat(document.getElementById("pctPrice").value);
  const d = parseFloat(document.getElementById("pctDisc").value);
  if (!isNaN(p) && !isNaN(d)) {
    const final = p - (p * d / 100);
    document.getElementById("pct4Res").textContent = `₹${final.toFixed(2)} (Save ₹${(p-final).toFixed(2)})`;
  } else { document.getElementById("pct4Res").textContent = "—"; }
}
function resetPct() {
  ["pct1X","pct1Y","pct2From","pct2To","pctMarks","pctTotal","pctPrice","pctDisc"].forEach(id => {
    const el = document.getElementById(id); if(el) el.value = "";
  });
  ["pct1Res","pct2Res","pct3Res","pct4Res"].forEach(id => {
    const el = document.getElementById(id); if(el) el.textContent = "—";
  });
}

// ===== TEXT CASE CONVERTER =====
function convertCase(type) {
  const input = document.getElementById("caseInput").value;
  if (!input.trim()) return showNotify("error", "Please enter some text first!");
  let out = "";
  switch(type) {
    case "upper":    out = input.toUpperCase(); break;
    case "lower":    out = input.toLowerCase(); break;
    case "title":    out = input.replace(/\w\S*/g, w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()); break;
    case "sentence": out = input.toLowerCase().replace(/(^\s*\w|[.!?]\s*\w)/g, c => c.toUpperCase()); break;
    case "camel":    out = input.toLowerCase().replace(/[^a-zA-Z0-9]+(.)/g, (_, c) => c.toUpperCase()); break;
    case "snake":    out = input.toLowerCase().trim().replace(/\s+/g, "_").replace(/[^a-z0-9_]/g, ""); break;
  }
  document.getElementById("caseOutput").value = out;
  document.getElementById("caseResultBox").classList.remove("d-none");
  showNotify("success", "Converted!");
}

// ===== STOPWATCH & TIMER =====
let swInterval = null, swRunning = false, swMs = 0, swLapCount = 0;
let timerInterval = null, timerRunning = false, timerLeft = 0;

function initStopwatch() { swReset(); timerReset(); }

function swFormat(ms) {
  const min = String(Math.floor(ms / 60000)).padStart(2,"0");
  const sec = String(Math.floor((ms % 60000) / 1000)).padStart(2,"0");
  const cs  = String(Math.floor((ms % 1000) / 10)).padStart(2,"0");
  return `${min}:${sec}.${cs}`;
}

function swStart() {
  const btn = document.getElementById("swStartBtn");
  if (!swRunning) {
    const start = Date.now() - swMs;
    swInterval = setInterval(() => {
      swMs = Date.now() - start;
      document.getElementById("swDisplay").textContent = swFormat(swMs);
    }, 10);
    swRunning = true;
    btn.innerHTML = '<i class="fas fa-pause me-1"></i>Pause';
    btn.className = "btn btn-warning px-4 fw-bold";
  } else {
    clearInterval(swInterval); swRunning = false;
    btn.innerHTML = '<i class="fas fa-play me-1"></i>Resume';
    btn.className = "btn btn-success px-4 fw-bold";
  }
}

function swLap() {
  if (!swRunning && swMs === 0) return;
  swLapCount++;
  const laps = document.getElementById("swLaps");
  const div = document.createElement("div");
  div.className = "d-flex justify-content-between small border-bottom py-1";
  div.innerHTML = `<span class="text-muted">Lap ${swLapCount}</span><span class="fw-bold font-monospace">${swFormat(swMs)}</span>`;
  laps.prepend(div);
}

function swReset() {
  clearInterval(swInterval); swRunning = false; swMs = 0; swLapCount = 0;
  const el = document.getElementById("swDisplay"); if(el) el.textContent = "00:00.00";
  const btn = document.getElementById("swStartBtn");
  if(btn) { btn.innerHTML = '<i class="fas fa-play me-1"></i>Start'; btn.className = "btn btn-success px-4 fw-bold"; }
  const laps = document.getElementById("swLaps"); if(laps) laps.innerHTML = "";
}

function timerStart() {
  const btn = document.getElementById("timerStartBtn");
  if (!timerRunning) {
    if (timerLeft === 0) {
      const m = parseInt(document.getElementById("timerMin").value) || 0;
      const s = parseInt(document.getElementById("timerSec").value) || 0;
      timerLeft = m * 60 + s;
      if (timerLeft <= 0) return showNotify("error", "Set a time first!");
    }
    timerRunning = true;
    btn.innerHTML = '<i class="fas fa-pause me-1"></i>Pause';
    btn.className = "btn btn-warning px-4 fw-bold";
    timerInterval = setInterval(() => {
      timerLeft--;
      const m = String(Math.floor(timerLeft / 60)).padStart(2,"0");
      const s = String(timerLeft % 60).padStart(2,"0");
      const el = document.getElementById("timerDisplay");
      if(el) { el.textContent = `${m}:${s}`; el.style.color = timerLeft <= 10 ? "#dc2626" : "#dc2626"; }
      if (timerLeft <= 0) {
        clearInterval(timerInterval); timerRunning = false;
        if(el) el.textContent = "00:00";
        if(btn) { btn.innerHTML = '<i class="fas fa-play me-1"></i>Start'; btn.className = "btn btn-danger px-4 fw-bold"; }
        showNotify("success", "⏰ Time's up!");
        try { new Audio("data:audio/wav;base64,UklGRnoGAABXQVZFZm10IBAAAA...").play(); } catch(e) {}
      }
    }, 1000);
  } else {
    clearInterval(timerInterval); timerRunning = false;
    btn.innerHTML = '<i class="fas fa-play me-1"></i>Resume';
    btn.className = "btn btn-danger px-4 fw-bold";
  }
}

function timerReset() {
  clearInterval(timerInterval); timerRunning = false; timerLeft = 0;
  const el = document.getElementById("timerDisplay"); if(el) { el.textContent = "00:00"; el.style.color = "#dc2626"; }
  const btn = document.getElementById("timerStartBtn");
  if(btn) { btn.innerHTML = '<i class="fas fa-play me-1"></i>Start'; btn.className = "btn btn-danger px-4 fw-bold"; }
  const m = document.getElementById("timerMin"); if(m) m.value = "";
  const s = document.getElementById("timerSec"); if(s) s.value = "";
}
